# Generated by Django 5.1.6 on 2025-04-19 23:57

import universityApps.admissions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Applicant's first name", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Applicant's last name", max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="Applicant's email address", max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(help_text="Applicant's phone number", max_length=20, verbose_name='Phone Number')),
                ('birth_date', models.DateField(help_text="Applicant's birth date", verbose_name='Birth Date')),
                ('national_id', models.CharField(help_text="Applicant's national ID number", max_length=30, verbose_name='National ID')),
                ('previous_qualifications', models.TextField(blank=True, null=True, verbose_name='Previous Qualifications')),
                ('qualification_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Qualification Average')),
                ('qualification_institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Where To Get the Qualification')),
                ('date_obtained', models.DateField(blank=True, null=True, verbose_name='Date Obtained')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('additional_info', 'Additional Info Required'), ('achieved', 'Achieved')], max_length=20, verbose_name='Status')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('high_school', 'High School Certificate'), ('photo', 'Personal Photo'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=universityApps.admissions.utils.application_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
