services:
  web:
    build: .
    container_name: django_app_dev
    command: python manage.py runserver 0.0.0.0:8000 --settings=project.settings.production
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: postgres_db_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_dev
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker_dev
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935" # RTMP
      - "8080:80" # HLS playback
    volumes:
      - ./media/rtmp/hls:/tmp/hls
      - ./media/rtmp/record:/tmp/record

volumes:
  postgres_data:
