# Generated by Django 5.1.6 on 2025-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
