# Generated by Django 5.1.6 on 2025-04-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_no', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='College Number')),
                ('code', models.CharField(editable=False, help_text='code (automatically generated from name', unique=True, verbose_name='College Code')),
                ('name', models.CharField(help_text='Full name of the college', max_length=255, verbose_name='College Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the college', null=True, verbose_name='College Description')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['code', 'college_no'],
            },
        ),
    ]
