# Generated by Django 5.1.6 on 2025-03-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('col_no', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='College Number')),
                ('code', models.IntegerField(editable=False, help_text='Unique numeric identifier for the college', unique=True, verbose_name='College Code')),
                ('name', models.CharField(help_text='Full name of the college', max_length=255, verbose_name='College Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the college', null=True, verbose_name='College Description')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['code', 'col_no'],
                'indexes': [models.Index(fields=['col_no', 'name'], name='college_col_no_name_idx')],
            },
        ),
    ]
