# Generated by Django 5.1.6 on 2025-03-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(editable=False, help_text='code (automatically generated from name', unique=True, verbose_name='College Code'),
        ),
    ]
