# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='dean',
            field=models.OneToOneField(blank=True, help_text='Dean of the college', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facultymember', verbose_name='Dean'),
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university', verbose_name='University'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_no', 'name'], name='college_college_no_name_idx'),
        ),
    ]
