# Generated by Django 5.1.6 on 2025-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_college_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['code', 'college_no'], 'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.RemoveIndex(
            model_name='college',
            name='college_col_no_name_idx',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='col_no',
            new_name='college_no',
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_no', 'name'], name='college_college_no_name_idx'),
        ),
    ]
