# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='course',
            field=models.ForeignKey(help_text='Course to which the semester course belongs', on_delete=django.db.models.deletion.CASCADE, related_name='course_semester', to='courses.course', verbose_name='Course'),
        ),
    ]
