# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterplan',
            name='academic_level',
            field=models.ForeignKey(help_text='Academic level to which the semester plan belongs', on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to='programs.academiclevel', verbose_name='Academic Level'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='semester_plan',
            field=models.ForeignKey(help_text='Semester plan to which the semester course belongs', on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='academic.semesterplan', verbose_name='Semester Plan'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program to which the study plan belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='programs.academicprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='study_plan',
            field=models.ForeignKey(help_text='Study plan to which the semester plan belongs', on_delete=django.db.models.deletion.CASCADE, related_name='Plan_semester_plans', to='academic.studyplan', verbose_name='Study Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_type')},
        ),
        migrations.AddIndex(
            model_name='semestercourse',
            index=models.Index(fields=['semester_plan'], name='semester_course_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='semestercourse',
            index=models.Index(fields=['order'], name='semester_course_order_idx'),
        ),
        migrations.AddIndex(
            model_name='semestercourse',
            index=models.Index(fields=['is_required'], name='semester_course_required_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semestercourse',
            unique_together={('semester_plan', 'course')},
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['status'], name='study_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['effective_from'], name='study_plan_effective_from_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together={('program', 'version')},
        ),
        migrations.AddIndex(
            model_name='semesterplan',
            index=models.Index(fields=['academic_level'], name='semester_plan_level_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterplan',
            index=models.Index(fields=['semester_type'], name='semester_plan_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semesterplan',
            unique_together={('study_plan', 'academic_level', 'semester_type')},
        ),
    ]
