# Generated by Django 5.1.6 on 2025-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterplan',
            name='name_ar',
            field=models.CharField(editable=False, help_text='Name of the semester plan', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='name_en',
            field=models.CharField(editable=False, help_text='Name of the semester plan', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
