# Generated by Django 5.1.6 on 2025-04-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_semester_add_drop_end_date_and_more'),
        ('users', '0002_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academic.studentgroup', verbose_name='Group')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='users.student', verbose_name='Student')),
            ],
        ),
    ]
