# Generated by Django 5.1.6 on 2025-04-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_classroom_groupschedule_lecturebroadcast_and_more'),
        ('users', '0002_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='academic.gradecomponent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.semestercourse')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.exam')),
            ],
            options={
                'verbose_name': 'Exam Section',
                'verbose_name_plural': 'Exam Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('is_mcq', models.BooleanField(default=False)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academic.examsection')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='academic.examquestion')),
            ],
            options={
                'verbose_name': 'MCQ Choice',
                'verbose_name_plural': 'MCQ Choices',
            },
        ),
        migrations.CreateModel(
            name='StudentExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academic.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Exam Submission',
                'verbose_name_plural': 'Student Exam Submissions',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.examquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.mcqchoice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academic.studentexamsubmission')),
            ],
            options={
                'verbose_name': 'Exam Answer',
                'verbose_name_plural': 'Exam Answers',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course'], name='exam_course_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['scheduled_date'], name='exam_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamsubmission',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('submission', 'question')},
        ),
    ]
