# Generated by Django 5.1.6 on 2025-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_exam_examsection_examquestion_mcqchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturebroadcast',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='scheduled', max_length=10, verbose_name='Status'),
        ),
    ]
