# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='University Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='University Description')),
                ('code', models.CharField(default='DUMS', help_text='Unique numeric identifier for the university', unique=True, verbose_name='University Code')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UniversityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Detail Title')),
                ('subtitle', models.TextField(verbose_name='Detail subtitle')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.university', verbose_name='University')),
            ],
        ),
    ]
