# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
import universityApps.departments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_no', models.IntegerField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='Department Number')),
                ('code', models.CharField(editable=False, help_text='Code (automatically generated from name)', max_length=255, unique=True, verbose_name='Department Code')),
                ('name', models.CharField(help_text='Name of the department', max_length=255, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, help_text='Description of the department', null=True, verbose_name='Department Description')),
                ('type', models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative')], help_text='Type of the department', max_length=255, verbose_name='Department Type')),
                ('image', models.ImageField(blank=True, help_text='Image of the department', null=True, upload_to=universityApps.departments.utils.department_image_path, verbose_name='Department Image')),
                ('depaertment_message', models.TextField(blank=True, help_text='Message to be displayed on the department page', null=True, verbose_name='Department Message')),
                ('department_vision', models.TextField(blank=True, help_text='Vision of the department', null=True, verbose_name='Department Vision')),
                ('college', models.OneToOneField(help_text='College to which the department belongs', on_delete=django.db.models.deletion.CASCADE, to='colleges.college', verbose_name='College')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code', 'dept_no', 'name', 'college', 'type'],
            },
        ),
    ]
