# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Head of the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='users.facultymember', verbose_name='Head of the Department'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['dept_no', 'name'], name='department_dept_no_name_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['college'], name='department_college_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='department_code_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type'], name='department_type_index'),
        ),
    ]
