# Generated by Django 5.1.6 on 2025-04-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_initial'),
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(help_text='College to which the department belongs', on_delete=django.db.models.deletion.CASCADE, to='colleges.college', verbose_name='College'),
        ),
    ]
