# Generated by Django 5.1.6 on 2025-04-20 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiclevel',
            name='program',
            field=models.ForeignKey(help_text='Program to which the level belongs', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='programs.academicprogram', verbose_name='Program'),
        ),
    ]
