# Generated by Django 5.1.6 on 2025-04-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_academiclevel_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='image',
            field=models.ImageField(default='mdkwmkd', help_text='Image of the program', upload_to='program_images', verbose_name='Program Image'),
            preserve_default=False,
        ),
    ]
