# Generated by Django 5.1.6 on 2025-04-19 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_initial'),
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(help_text='Course to which the module belongs', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(help_text='Module to which the content belongs', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='subject',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College to which the subject belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_subjects', to='colleges.college', verbose_name="Subject's College"),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department to which the subject belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_subjects', to='departments.department', verbose_name="Subject's Department"),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='Subject of the course', on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['order'], name='module_order_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course'], name='module_course_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subject_code_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['slug'], name='subject_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='course_code_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='course_type_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject'], name='course_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='course_slug_idx'),
        ),
    ]
